version: '3.8'

services:
  zookeeper:
    image: 'zookeeper:3.7'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: 'apache/kafka:3.8.1'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  spark-master:
    image: 'apache/spark:3.5.3'
    command: >
      bash -c "start-master.sh && tail -f /dev/null"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-network

  spark-worker:
    image: 'apache/spark:3.5.3'
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    networks:
      - spark-network

  mariadb:
    image: 'mariadb:10.5'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "53306:3306"
    networks:
      - backend-network

  airflow:
    image: 'apache/airflow:2.10.3-python3.11'
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+pymysql://example_user:example_password@mariadb:3306/example_db'
    depends_on:
      - mariadb
    ports:
      - "8081:8081"
    networks:
      - backend-network

  spring-app:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:53306/example_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - mariadb
    ports:
      - "8082:8080"
    networks:
      - backend-network

networks:
  backend-network:
  kafka-network:
  spark-network:

