services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - "53306:3306"
    networks:
      - all_network

  spring-app:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/example_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mariadb
    ports:
      - "8082:8082"
    networks:
      - all_network

networks:
  all_network:
