services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: codulgi
      MARIADB_PASSWORD: codul1234
      MARIADB_DATABASE: codulgi_db
    ports:
      - "3366:3306"
    volumes:
      - ../volume/mariadb/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - all_network

  spring-app:
    container_name: spring-app
    build:
      context: dockerfiles/spring-app
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8082:8080"
    networks:
      - all_network

networks:
  all_network:
